#! /usr/bin/env python

Import('ENV', 'common_example')

sources = {
  'simple-loop.asm': []
}

common_example(ENV, 'simple-loop', sources = sources, link_args = {'SECTION_BASES': ['.text=0x00000000']})

ENV.Help("""
     ${BLUE}'scons simple-loop'${CLR} to build "simple loop" benchmark,
     ${BLUE}'scons run-simple-loop'${CLR} to run "simple loop" benchmark,
""")
