#! /usr/bin/env python

Import('ENV', 'common_example')

common_example(ENV, 'simple-loop')

ENV.Help("""
     ${BLUE}'scons simple-loop'${CLR} to build "simple loop" benchmark,
     ${BLUE}'scons run-simple-loop'${CLR} to run "simple loop" benchmark,
""")
