include $(TOPDIR)/Makefile.inc

TESTSUITEDIR := $(CURDIR)/src

# See tests/forth/ans/runtest.fth for full list
FORTH_ANS_TESTS := prelimtest.fth tester.fr core.fr coreplustest.fth utilities.fth errorreport.fth 


TC_DIR      := $(TC_DIR)/ans
TC_OUTPUT   := $(TC_DIR)/forth-ans.$(DB_PID).out
TC_MACHINE  := $(TC_DIR)/forth-ans.$(DB_PID).machine
TC_FILTERED := $(TC_DIR)/forth-ans.$(DB_PID).filtered

ifeq ($(VMCOVERAGE),yes)
  COVERAGE_FILE := $(TESTSETDIR)/coverage/.coverage.forth-ans.$(DB_PID)
else
  COVERAGE_FILE :=
endif

export COVERAGE_FILE


tests-pre:
	$(Q) mkdir -p $(TC_DIR)

tests:
	$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) FORTH ANS testsuite ... "
	$(Q) $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) \
			 $(VMPROFILE) \
			 $(BINPROFILE) -g \
			 --machine-config=$(TC_CONFIG) \
			 --set-option=bootloader:file=$(FORTH_KERNEL) \
			 --set-option=device-3:streams_in=$(CURDIR)/../enable-test-mode.f \
			 --add-option=device-3:streams_in=$(TOPDIR)/forth/ducky-forth.f \
			 $(foreach testfile,$(FORTH_ANS_TESTS),--add-option=device-3:streams_in=$(TESTSUITEDIR)/$(testfile)) \
			 --add-option=device-3:streams_in=$(TOPDIR)/tests/forth/ans-report.f \
			 --set-option=device-3:stream_out=$(TC_OUTPUT) \
			 $(foreach device,$(DUCKY_ENABLE_DEVICES),--enable-device=$(device)) \
			 $(foreach device,$(DUCKY_DISABLE_DEVICES),--disable-device=$(device)) \
			 $(VMDEBUG) $(VMDEBUG_OPEN_FILES) &> $(TC_MACHINE); \
			 if [[ $$? -ne 0 ]]; then \
			   $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name="ANS test suite" --result=fail --message="Invalid exit code" --diff=$(TC_MACHINE); \
			   touch $(TESTSET_FAILED); \
				 echo "$(CC_RED)FAIL$(CC_END)"; \
			 else \
			   grep -v -e '\[INFO\] ' -e '#> ' $(TC_MACHINE) || /bin/true; \
				 grep -e 'INCORRECT RESULT' -e 'WRONG NUMBER OF RESULTS' $(TC_OUTPUT) > $(TC_FILTERED) || /bin/true; \
				 if [ ! -s $(TC_FILTERED) ]; then \
	         $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name="ANS test suite"; \
					 echo "$(CC_GREEN)PASS$(CC_END)"; \
				 else \
				   $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name="ANS test suite" --result=fail --message="Failed aserts" --diff=$(TC_FILTERED); \
					 sed -e 's/^/  /' $(TC_FILTERED); \
					 touch $(TESTSET_FAILED); \
				   echo "$(CC_RED)FAIL$(CC_END)"; \
				 fi; \
			 fi; \
			 exit 0;

tests-post:

clean:
