#! /usr/bin/env python

import os

Import('ENV')

E = ENV.FullClone()
E.PassVarAsDefine('BOOT_IMAGE')

E.DuckyObject('loader.o', source = 'loader.s')
E.DuckyBinary('loader', source = ['loader.o'])
E.ReadExternalDeps()
ENV.Command('loader.img', 'loader', E.DuckyImage('loader.img', 'loader'))

E.Alias('loader', File('loader'))
E.Alias('loader-image', File('loader.img'))

E.OnClean(['loader', 'loader-image'])
E.Help("""
  ${GREEN}Boot loader:${CLR}
     ${BLUE}'scons loader'${CLR} to build basic boot loader,
     ${BLUE}'scons loader-image'${CLR} to build basic boot loader image
""")
