#!/usr/bin/env python

import sys

insts = 0
secs = 0

lines = [(float(l[0]), float(l[1])) for l in [line.strip().split() for line in sys.stdin]]

print sum([l[0] for l in lines]) / sum([l[1] for l in lines])
