#!/usr/bin/env python

import sys
import time
import xunitgen

if len(sys.argv) == 1:
  print 'xunit-record <output file> <tc name> <tc file>'

OUTPUT = sys.argv[1]
TC = sys.argv[2]
FILE = sys.argv[3]

receiver = xunitgen.EventReceiver()

receiver.begin_case(TC, time.time(), FILE)

if len(sys.argv) > 4:
  RESULT = sys.argv[4]

  if RESULT == 'fail':
    receiver.failure(sys.argv[5], sys.argv[6])

  elif RESULT == 'error':
    receiver.error(sys.argv[5])
  
receiver.end_case(TC, time.time())

with open(OUTPUT, 'w') as f:
  f.write(xunitgen.toxml(receiver.results(), 'forth-tests'))

