: STAR 2A EMIT ;
: TOP 0 DO STAR LOOP CR ;
: BOTTOM TOP ;
: MIDDLE STAR 2 - 0 DO SPACE LOOP STAR CR ;
: BOX ( width height -- ) CR OVER TOP 2 - 0 DO DUP MIDDLE LOOP BOTTOM ;

20 10 BOX
10 20 BOX
3 3 BOX
