T{ : TEST-STACK-CELLS S" STACK-CELLS" ENVIRONMENT? ; -> }T
T{ : TEST-RETURN-STACK-CELLS S" RETURN-STACK-CELLS" ENVIRONMENT? ; -> }T
T{ : TEST-COUNTED-STRING S" /COUNTED-STRING" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-U S" MAX-U" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-N S" MAX-N" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-UD S" MAX-UD" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-D S" MAX-D" ENVIRONMENT? ; -> }T
T{ : TEST-ADDRESS-UNIT-BITS S" ADDRESS-UNIT-BITS" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-CHAR S" MAX-CHAR"    ENVIRONMENT? ; -> }T
T{ : TEST-FLOORED  S" FLOORED"     ENVIRONMENT? ; -> }T
T{ : TEST-CORE-EXT S" CORE-EXT"    ENVIRONMENT? ; -> }T
T{ : TEST-CORE     S" CORE"        ENVIRONMENT? ; -> }T
T{ : TEST-UNKNOWN  S" UNKNOWN-ENV" ENVIRONMENT? ; -> }T
T{ : TEST-BLOCK     S" BLOCK"       ENVIRONMENT? ; -> }T
T{ : TEST-BLOCK-EXT S" BLOCK-EXT"   ENVIRONMENT? ; -> }T

T{ TEST-STACK-CELLS -> 40 TRUE }T
T{ TEST-RETURN-STACK-CELLS -> 40 TRUE }T
T{ TEST-COUNTED-STRING -> FF TRUE }T
T{ TEST-MAX-U -> FFFFFFFF TRUE }T
T{ TEST-MAX-N -> 0 INVERT 1 RSHIFT TRUE }T
T{ TEST-MAX-UD -> FFFFFFFF FFFFFFFF TRUE }T
T{ TEST-MAX-D -> FFFFFFFF 0 INVERT 1 RSHIFT TRUE }T
T{ TEST-ADDRESS-UNIT-BITS -> 8 TRUE }T
T{ TEST-MAX-CHAR -> 7F TRUE }T
T{ TEST-FLOORED -> TRUE TRUE }T
T{ TEST-CORE-EXT -> FALSE TRUE }T
T{ TEST-CORE -> FALSE TRUE }T
T{ TEST-UNKNOWN -> FALSE }T
T{ TEST-BLOCK -> TRUE TRUE }T
T{ TEST-BLOCK-EXT -> TRUE TRUE }T
