T{ : TEST-STACK-CELLS S" STACK-CELLS" ENVIRONMENT? ; -> }T
T{ : TEST-RETURN-STACK-CELLS S" RETURN-STACK-CELLS" ENVIRONMENT? ; -> }T
T{ : TEST-COUNTED-STRING S" /COUNTED-STRING" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-U S" MAX-U" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-N S" MAX-N" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-UD S" MAX-UD" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-D S" MAX-D" ENVIRONMENT? ; -> }T
T{ : TEST-ADDRESS-UNIT-BITS S" ADDRESS-UNIT-BITS" ENVIRONMENT? ; -> }T
T{ : TEST-MAX-CHAR S" MAX-CHAR" ENVIRONMENT? ; -> }T
T{ : TEST-FLOORED S" FLOORED" ENVIRONMENT? ; -> }T
T{ : TEST-CORE-EXT S" CORE-EXT" ENVIRONMENT? ; -> }T
T{ : TEST-CORE S" CORE" ENVIRONMENT? ; -> }T
T{ : TEST-UNKNOWN S" UNKNOWN-ENV" ENVIRONMENT? ; -> }T

T{ TEST-STACK-CELLS -> TRUE 40 }T
T{ TEST-RETURN-STACK-CELLS -> TRUE 40 }T
T{ TEST-COUNTED-STRING -> TRUE FF }T
T{ TEST-MAX-U -> TRUE FFFFFFFF }T
T{ TEST-MAX-N -> TRUE 0 INVERT 1 RSHIFT }T
T{ TEST-MAX-UD -> TRUE FFFFFFFF FFFFFFFF }T
T{ TEST-MAX-D -> TRUE FFFFFFFF 0 INVERT 1 RSHIFT }T
T{ TEST-ADDRESS-UNIT-BITS -> TRUE 8 }T
T{ TEST-MAX-CHAR -> TRUE 7F }T
T{ TEST-FLOORED -> TRUE TRUE }T
T{ TEST-CORE-EXT -> TRUE FALSE }T
T{ TEST-CORE -> TRUE FALSE }T
T{ TEST-UNKNOWN -> FALSE }T
