0 INVERT      CONSTANT MAX-UINT
0 INVERT 1 RSHIFT   CONSTANT MAX-INT
0 INVERT 1 RSHIFT INVERT  CONSTANT MIN-INT

." MAX-INT  " MAX-INT  DUP . U. CR
." MIN-INT  " MIN-INT  DUP . U. CR
." MAX-UINT " MAX-UINT DUP . U. CR
." MIN-UINT " 0        DUP . U. CR

