0 INVERT      CONSTANT MAX-UINT
0 INVERT 1 RSHIFT   CONSTANT MAX-INT
0 INVERT 1 RSHIFT INVERT  CONSTANT MIN-INT

: TEST-MAX-INT  ." MAX-INT  " MAX-INT  DUP . U. CR ;
: TEST-MIN-INT  ." MIN-INT  " MIN-INT  DUP . U. CR ;
: TEST-MAX-UINT ." MAX-UINT " MAX-UINT DUP . U. CR ;
: TEST-MIN-UINT ." MIN-UINT " 0        DUP . U. CR ;

TEST-MAX-INT TEST-MIN-INT TEST-MAX-UINT TEST-MIN-UINT
