#! /usr/bin/env python

Import('ENV', 'common_example')

common_example(ENV, 'hello-world')

ENV.Help("""
     ${BLUE}'scons hello-world'${CLR} to build "Hello, world!" example,
     ${BLUE}'scons run-hello-world'${CLR} to run "Hello, world!" example,
""")
