#! /usr/bin/env python

Import('ENV', 'common_example')

sources = {
  'hello-world.asm': ENV.GetDuckyDefine('tty')
}

common_example(ENV, 'hello-world', sources = sources, link_args = {'SECTION_BASES': ['.text=0x00000000']})

ENV.Help("""
     ${BLUE}'scons hello-world'${CLR} to build "Hello, world!" example,
     ${BLUE}'scons run-hello-world'${CLR} to run "Hello, world!" example,
""")
