#! /usr/bin/env python

Import('ENV', 'common_example')

sources = {
  'fib.asm': []
}

common_example(ENV, 'fib', sources = sources, link_args = {'SECTION_BASES': ['.text=0x00000000']})

ENV.Help("""
     ${BLUE}'scons fib'${CLR} to build "Hello, world!" example,
     ${BLUE}'scons run-fib'${CLR} to run "Hello, world!" example,
""")
