#! /usr/bin/env python

Import('ENV', 'common_example')

common_example(ENV, 'fib')

ENV.Help("""
     ${BLUE}'scons fib'${CLR} to build "Hello, world!" example,
     ${BLUE}'scons run-fib'${CLR} to run "Hello, world!" example,
""")
