FROM python:3.5.1-alpine

MAINTAINER Milos Prchlik <happz@happz.cz>

ENV VIRTUAL_ENV=/usr/local

RUN apk update && apk add make bash wget curl jq scons git

# Fetch the last built FORTH kernel
# This is a necessary workaround, because it's not possible to build
# it directly in the image, since scons does not support Python 3.
ADD http://fanny.happz.cz/~happz/ducky-forth/latest/ducky-forth /tmp/
ADD http://fanny.happz.cz/~happz/ducky-forth/latest/ducky-forth.f /tmp/
ADD http://fanny.happz.cz/~happz/ducky-forth/latest/forth.conf /tmp/

RUN mkdir -p /home && wget -O /home/ducky.zip --no-check-certificate https://github.com/happz/ducky/archive/master.zip && cd /home && unzip ducky.zip && mv ducky-master ducky && cd /home/ducky && make install-edit

ENV PYTHONUNBUFFERED=yes

ENTRYPOINT ["/usr/local/bin/python", \
            "-OO", \
            "/usr/local/bin/ducky-vm", \
            "-g", \
            "--machine-config=/tmp/forth.conf", \
            "--set-option=bootloader:file=/tmp/ducky-forth", \
            "--set-option=device-3:streams_in=/tmp/ducky-forth.f", \
            "--add-option=device-3:streams_in=<stdin>", \
            "--set-option=device-3:stream_out=<stderr>", \
            "--set-option=device-3:echo=no", \
            "--jit" \
           ]
