#! /usr/bin/env python

Import('ENV')

ENV.DuckyObject('smp.o', source = 'smp.s')
ENV.ReadExternalDeps()

ENV.DuckyBinary('smp', source = ['smp.o'])
ENV.Command('smp.img', 'smp', ENV.DuckyImage('smp.img', 'smp', bio = True))

smp = ENV.Alias('smp', File('smp'))

ENV.Command('.running-smp', [File('smp'), 'smp.img'], ENV.DuckyRun(config = 'smp.conf', set_options = ['bootloader:file=%s' % File('#boot/loader').abspath, 'device-6:filepath=%s' % File('smp.img').abspath], expected_exit = 1))

run_smp = ENV.Alias('run-smp', '.running-smp')
ENV.Depends('.running-smp', File('#boot/loader'))

ENV.Depends('examples', 'smp')

ENV.Help("""
     ${BLUE}'scons smp'${CLR} to build SMP example,
     ${BLUE}'scons run-smp'${CLR} to run SMP examples,
""")
