#! /usr/bin/env python

Import('ENV', 'common_example')

sources = {
        'exceptions.asm': ENV.GetDuckyDefine('tty', 'ducky', 'boot')
}

common_example(ENV, 'exceptions', sources = sources, link_args = {'SECTION_BASES': ['.text=0x00000000']})

ENV.Help("""
     ${BLUE}'scons exceptions'${CLR} to build Exceptions example,
     ${BLUE}'scons run-exceptions'${CLR} to run Exceptions example,
""")
