#! /usr/bin/env python

Import('ENV', 'common_example')

common_example(ENV, 'exceptions')

ENV.Help("""
     ${BLUE}'scons exceptions'${CLR} to build Exceptions example,
     ${BLUE}'scons run-exceptions'${CLR} to run Exceptions example,
""")
