#! /usr/bin/env python

Import('ENV', 'common_example')

common_example(ENV, 'echo')

ENV.Help("""
     ${BLUE}'scons echo'${CLR} to build Echo example,
     ${BLUE}'scons run-echo'${CLR} to run Echo example,
""")
