#! /usr/bin/env python

Import('ENV', 'common_example')

sources = {
  'echo.asm': ENV.GetDuckyDefine('tty', 'keyboard')
}

common_example(ENV, 'echo', sources = sources, link_args = {'SECTION_BASES': ['.text=0x00000000']})

ENV.Help("""
     ${BLUE}'scons echo'${CLR} to build Echo example,
     ${BLUE}'scons run-echo'${CLR} to run Echo example,
""")
