#! /usr/bin/env python

Import('ENV', 'common_example')

common_example(ENV, 'hello-world', alias_name = 'hello-world-lib', sources = ['main.s', 'lib.s'])

ENV.Help("""
     ${BLUE}'scons hello-world-lib'${CLR} to build another "Hello, world!" example,
     ${BLUE}'scons run-hello-world-lib'${CLR} to run this another "Hello, world!" examples,
""")
