#! /usr/bin/env python

Import('ENV', 'common_example')

common_example(ENV, 'clock')

ENV.Help("""
     ${BLUE}'scons clock'${CLR} to build "Hello, world!" example,
     ${BLUE}'scons run-clock'${CLR} to run "Hello, world!" example,
""")
