#! /usr/bin/env python

Import('ENV', 'common_example')

sources = {
  'clock.asm': ENV.GetDuckyDefine('ducky', 'rtc', 'svga')
}

common_example(ENV, 'clock', sources = sources, link_args = {'SECTION_BASES': ['.text=0x00000000']})

ENV.Help("""
     ${BLUE}'scons clock'${CLR} to build "Hello, world!" example,
     ${BLUE}'scons run-clock'${CLR} to run "Hello, world!" example,
""")
