#! /usr/bin/env python

Import('ENV', 'common_example')

sources = {
  'vga.asm': ENV.GetDuckyDefine('ducky', 'svga')
}

common_example(ENV, 'vga', sources = sources, link_args = {'SECTION_BASES': ['.text=0x00000000']})

ENV.Help("""
     ${BLUE}'scons vga'${CLR} to build VGA example,
     ${BLUE}'scons run-vga'${CLR} to run VGA example,
""")
