#! /usr/bin/env python

Import('ENV', 'common_example')

common_example(ENV, 'vga')

ENV.Help("""
     ${BLUE}'scons vga'${CLR} to build VGA example,
     ${BLUE}'scons run-vga'${CLR} to run VGA example,
""")
